### ISSUE TITLE
Error when scanning QR code from non-Safe address

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-ios#101] opened 2020-05-12 15:41 UTC
I'm using 0.2.0 of the app.

- Add new Safe
- Scan QR code of: `0x0e329fa8d6fcd1ba0cda495431f1f7ca24f442c2` (image below)
-> Some http error (Screenshot attached below)

Expected result: https://zpl.io/aNQq3GN

### Error
![IMG_9132](https://user-images.githubusercontent.com/1380529/81714638-8c0e7c00-9477-11ea-843f-0533b230e5f0.PNG)

### QR code
![image](https://user-images.githubusercontent.com/1380529/81714351-43ef5980-9477-11ea-8773-04026c0a37be.png)

**Comment by sche** [comment] 2020-05-20 09:56
duplicate of #77

**Closed** 2020-05-20 09:56 UTC
Labels: bug
