### ISSUE TITLE
[IOS]Enter safe address menu view 

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-ios#221] opened 2020-06-10 09:37 UTC
1. Load Safe multisig page
2. Click Enter address

Current result: ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/74c17ec7-dd46-4699-a22e-b636560c664f)
Expected result: https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/5e8f2d58228c3621ade1daf6
1. Remove title for the menu
2. Keep "Enter ENS name" 

Questions:
1. Do we need menu title?
2.Enter ENS name is used instead of ENS name, but I like it as we have Paste ...., Scan.... and Enter looks just right here. Will we leave it?

**Comment by posthnikova** [comment] 2020-06-10 10:11
@liliya-soroka 
1. I think it's clear without the title
2. Let's keep 'Enter ENS Name'

**Comment by DmitryBespalov** [comment] 2020-06-15 09:25
Sorry to make it not a bug but a question again, but please bear in  mind:

1. is the duplicate of this bug/question - https://github.com/gnosis/safe-ios/issues/59 - there @posthnikova  decided to keep the title. The reason is that due to technical limitations of the current SDK we either can have the text in the title or an "empty" blank header, and we decided to keep it as text.

**Closed** 2020-06-18 08:22 UTC
Labels: bug, question, wontfix
